import React, { createContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // Header
    'header.home': 'Home',
    'header.shop': 'Shop',
    'header.programs': 'Programs',
    'header.calculator': 'Calorie Calculator',
    'header.calorieCalculator': 'Calorie Calculator',
    'header.contact': 'About Me',
    'header.feedback': 'Feedback',
    'header.guides': 'Guides',
    'header.cart': 'Cart',
    'header.admin': 'Admin',
    'header.logout': 'Logout',
    
    // Cart
    'cart.title': 'Shopping Cart',
    'cart.empty': 'Your cart is empty',
    'cart.emptyDesc': 'Looks like you haven\'t added any items to your cart yet.',
    'cart.continueShopping': 'Continue Shopping',
    'cart.items': 'item',
    'cart.itemsPlural': 'items',
    'cart.inCart': 'in your cart',
    'cart.subtotal': 'Subtotal',
    'cart.shipping': 'Shipping',
    'cart.tax': 'Tax',
    'cart.total': 'Total',
    'cart.freeShipping': 'Free',
    'cart.freeShippingProgress': 'Free Shipping Progress',
    'cart.addMore': 'Add {amount} DA more for free shipping!',
    'cart.freeShippingQualified': 'You qualify for free shipping!',
    'cart.proceedToCheckout': 'Proceed to Checkout',
    'cart.features.freeShipping': 'Free Shipping',
    'cart.features.securePayment': 'Secure Payment',
    'cart.features.support': '24/7 Support',
    
    // Product Detail
    'product.addToCart': 'Add to Cart',
    'product.buyNow': 'Buy Now',
    'product.outOfStock': 'Out of Stock',
    'product.inStock': 'In Stock',
    'product.lowStock': 'Low Stock',
    'product.lowStockWarning': 'Low stock. Order soon.',
    'product.quantity': 'Quantity',
    'product.size': 'Size',
    'product.color': 'Color',
    'product.description': 'Description',
    'product.specifications': 'Specifications',
    'product.usage': 'Usage',
    'product.noSpecs': 'No specifications available.',
    'product.reviews': 'reviews',
    'product.category': 'Category',
    'product.status': 'Status',
    'product.youMayAlsoLike': 'You May Also Like',
    
    // Order
    'order.title': 'Complete Your Order',
    'order.subtitle': 'Review product details and fill in your information',
    'order.productDetails': 'Product Details',
    'order.clientInfo': 'Client Information',
    'order.fullName': 'Full Name',
    'order.phone': 'Phone Number',
    'order.deliveryType': 'Delivery Type',
    'order.deliveryHome': 'Home',
    'order.deliveryHomeDesc': 'Delivery to your address',
    'order.deliveryStopDesk': 'Stop Desk',
    'order.deliveryStopDeskDesc': 'Pick up from delivery point (30% off)',
    'order.wilaya': 'Wilaya',
    'order.selectWilaya': 'Select Wilaya',
    'order.selectCommune': 'Select Commune',
    'order.commune': 'Commune',
    'order.exactAddress': 'Exact Address',
    'order.exactAddressOptional': '(Optional)',
    'order.exactAddressPlaceholder': 'Street address, building number, apartment, etc.',
    'order.orderSummary': 'Order Summary',
    'order.delivery': 'Delivery',
    'order.placeOrder': 'Place Order',
    'order.processing': 'Processing...',
    'order.confirmed': 'Order Confirmed!',
    'order.successSingle': 'Your order for',
    'order.successMultiple': 'Your order for',
    'order.successEnd': 'has been placed successfully.',
    'order.successItems': 'item',
    'order.successItemsPlural': 'items',
    'order.redirecting': 'Redirecting to homepage...',
    'order.note': 'Note:',
    'order.noteText': 'You will receive a confirmation call after placing your order.',
    'order.required': '*',
    
    // Shop
    'shop.title': 'Shop',
    'shop.filter': 'Filter',
    'shop.sort': 'Sort',
    'shop.allCategories': 'All Categories',
    'shop.priceRange': 'Price Range',
    'shop.search': 'Search products...',
    'shop.noProducts': 'No products found',
    'shop.loading': 'Loading...',
    'shop.sortName': 'Name (A-Z)',
    'shop.sortPriceLow': 'Price (Low to High)',
    'shop.sortPriceHigh': 'Price (High to Low)',
    'shop.sortRating': 'Top Rated',
    'shop.noProductsDesc': 'We couldn\'t find any products matching your filters.',
    'shop.buyingGuideTitle': 'How to Choose the Right Calisthenics Equipment',
    'shop.buyingGuideIntro': 'Whether you\'re building a home gym or upgrading your setup, the right equipment makes a real difference. Look for solid steel construction, clear weight limits, and secure fixings—especially for wall-mounted bars and dip stations.',
    'shop.buyingGuideOutro': 'Need more detail? Check our Guides for in-depth advice on pull-up bars, parallettes, and getting started with calisthenics.',
    
    // Home
    'home.shopByCategory': 'SHOP BY CATEGORY',
    'home.shopByCategoryDesc': 'Find the perfect equipment tailored to your training needs.',
    'home.bestseller': 'Best Seller',
    'home.toprated': 'Top Rated',
    'home.essential': 'Essential',
    'home.builtforathletes': 'Built for Athletes',
    'home.builtforathletesDesc': 'Professional-grade equipment designed by calisthenics experts',
    'home.fastdelivery': 'Fast Delivery',
    'home.fastdeliveryDesc': 'Quick shipping across Algeria - get your gear in 24-48 hours',
    'home.premiumquality': 'Premium Quality',
    'home.premiumqualityDesc': 'Durable, battle-tested materials that last for years',
    'home.localsupport': 'Local Support',
    'home.localsupportDesc': 'Expert customer service in Algeria - we speak your language',
    'home.bestSellers': 'BEST SELLERS',
    'home.topRated': 'Top-rated gear chosen by champions.',
    'home.viewAll': 'View All',
    'home.startJourney': 'Start Your',
    'home.journey': 'Journey',
    'home.journeyDesc': 'Equip yourself with the best tools in the game. Join the movement today.',
    'home.guidesTitle': 'Guides & Tips',
    'home.guidesDesc': 'Expert advice on equipment, calisthenics, and training at home.',
    'home.readGuides': 'Read Guides',
    'home.programGeneratorTitle': 'Free Workout Program Generator',
    'home.programGeneratorDesc': 'Get a personalized 1-week calisthenics program based on your level and max reps. Enter your numbers, generate your plan, and download a PDF to follow.',
    'home.generateProgram': 'Generate Program',
    'home.calorieCalculatorTitle': 'Calorie Calculator',
    'home.calorieCalculatorDesc': 'Calculate your daily calories and macro targets (protein, carbs, fat) based on your age, weight, height, and activity level. Reach your fitness goals with the right nutrition.',
    'home.calculateCalories': 'Calculate Calories',
    // Guides
    'guides.title': 'Guides & Tips',
    'guides.subtitle': 'Expert advice on choosing equipment, getting started with calisthenics, and training safely at home.',
    'guides.readMore': 'Read full guide',
    'guides.backToGuides': 'Back to all guides',
    'guides.pullUpBar': 'How to Choose a Pull-Up Bar',
    'guides.pullUpBarDesc': 'Material, weight capacity, installation, and safety tips for wall-mounted and freestanding bars.',
    'guides.equipmentGuide': 'Calisthenics Equipment Guide',
    'guides.equipmentGuideDesc': 'What to buy first: pull-up bars, parallettes, resistance bands, and more.',
    'guides.gettingStarted': 'Getting Started with Calisthenics',
    'guides.gettingStartedDesc': 'Building a routine, progressing safely, and staying consistent with bodyweight training.',
    'home.shopNow': 'Shop Now',
    'home.fastShipping': 'Fast Shipping',
    'home.securePayment': 'Secure Payment',
    'home.support24': '24/7 Support',
    
    // About Me (formerly Contact)
    'aboutMe.title': 'About Me',
    'aboutMe.subtitle': 'Professional calisthenics athlete & founder of Toufik Calisthenics',
    'aboutMe.metaDesc': 'Toufik Rahmani – Algerian professional competitive calisthenics athlete. 2× National Champion, 3rd place WSWCF World Championship Sofia.',
    'aboutMe.whoAmI': 'Who am I',
    'aboutMe.intro': 'Toufik Rahmani — Algerian professional competitive calisthenics athlete with over five years of experience and multiple national and international titles.',
    'aboutMe.experience': 'Experience & Background',
    'aboutMe.experienceDesc': 'More than five years of dedicated training and competition in calisthenics. Professional athlete representing Algeria on national and world stages.',
    'aboutMe.achievements': 'Achievements',
    'aboutMe.nationalChampion': 'National Champion',
    'aboutMe.nationalChampionDesc': '2× First Place — National Champion in Endurance.',
    'aboutMe.wswcf': 'WSWCF World Championship',
    'aboutMe.wswcfDesc': '3rd Place — WSWCF World Championship, Sofia (Strength).',
    'aboutMe.fiboArabia': 'Fibo Arabia Cup',
    'aboutMe.fiboArabiaDesc': '4th Place — Fibo Arabia Endurance Calisthenics Cup.',
    'aboutMe.getInTouch': 'Get in Touch',
    'aboutMe.chatWhatsApp': 'Chat on WhatsApp',
    'aboutMe.whatsappMessage': 'Hello Toufik! I would like to know more.',
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Have a question or need assistance? We\'re here to help!',
    'contact.sendMessage': 'Send Us a Message',
    'contact.name': 'Full Name',
    'contact.email': 'Email Address',
    'contact.subject': 'Subject',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.phone': 'Phone',
    'contact.location': 'Location',
    'contact.followUs': 'Follow Us',
    'contact.formDesc': 'We\'ll get back to you within 24 hours.',
    'contact.whatsappMessage': 'Hello REPS-DZ! I would like to know more about your products.',
    'contact.subjectPlaceholder': 'How can we help?',
    'contact.messagePlaceholder': 'Your message here...',
    
    // Footer
    'footer.about': 'About',
    'footer.quickLinks': 'Quick Links',
    'footer.contact': 'Contact',
    'footer.followUs': 'Follow Us',
    'footer.rights': 'All rights reserved.',
    
    // Common
    'common.back': 'Back',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.close': 'Close',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.clear': 'Clear',
    'common.result': 'Result',
    'common.results': 'Results',
    'common.show': 'Show',

    // Calorie Calculator page
    'calorie.title': 'Calorie & Macro',
    'calorie.calculator': 'Calculator',
    'calorie.subtitle': 'Calculate your daily caloric needs and macronutrient targets based on your body metrics and activity level',
    'calorie.wantFullGuide': 'Want to understand calories to lose fat?',
    'calorie.readCaloriesGuide': 'Read our full Calories guide',
    'calorie.yourInfo': 'Your Information',
    'calorie.yourName': 'Your name',
    'calorie.yourNamePlaceholder': 'e.g. Ahmed',
    'calorie.gender': 'Gender',
    'calorie.male': 'Male',
    'calorie.female': 'Female',
    'calorie.height': 'Height (cm)',
    'calorie.weight': 'Weight (kg)',
    'calorie.age': 'Age (years)',
    'calorie.activityLevel': 'Activity Level',
    'calorie.selectActivity': 'Select activity level',
    'calorie.activityLow': 'Low (sedentary, minimal exercise)',
    'calorie.activityModerate': 'Moderate (3-5 days/week exercise)',
    'calorie.activityHigh': 'High (6-7 days/week, intense training)',
    'calorie.calculate': 'Calculate',
    'calorie.calculating': 'Calculating...',
    'calorie.errorSelectGender': 'Please select your gender',
    'calorie.errorHeight': 'Please enter a valid height (1-250 cm)',
    'calorie.errorWeight': 'Please enter a valid weight (1-300 kg)',
    'calorie.errorAge': 'Please enter a valid age (1-120 years)',
    'calorie.errorGeneric': 'Error calculating. Please check your inputs and try again.',
    'calorie.dailyTarget': 'Daily caloric target',
    'calorie.basedOnProfile': 'Based on your profile and activity level',
    'calorie.bmrAtRest': 'BMR (at rest)',
    'calorie.bmrDesc': 'Calories your body burns at complete rest (Mifflin-St Jeor)',
    'calorie.macroTargets': 'Macronutrient targets',
    'calorie.perDay': '/day',
    'calorie.fiberNote': 'Fiber:',
    'calorie.fiberRecommended': 'g/day recommended (14g per 1000 kcal)',
    'calorie.fitnessTips': 'Fitness tips',
    'calorie.macroCalories': 'Calories',
    'calorie.macroProtein': 'Protein',
    'calorie.macroCarbs': 'Carbs',
    'calorie.macroFat': 'Fat',
    'calorie.macroFiber': 'Fiber',
    'calorie.tip1Title': 'Protein Timing',
    'calorie.tip1Text': 'Aim to consume 20-30g of protein within 30 minutes after your workout for optimal muscle recovery and growth.',
    'calorie.tip2Title': 'Stay Hydrated',
    'calorie.tip2Text': 'Drink at least 2-3 liters of water daily. Your muscles need proper hydration to perform and recover effectively.',
    'calorie.tip3Title': 'Recovery & Sleep',
    'calorie.tip3Text': 'Prioritize 7-9 hours of quality sleep. Growth hormone production peaks during deep sleep, essential for muscle recovery.',
    'calorie.tip4Title': 'Strength Nutrition',
    'calorie.tip4Text': 'For strength training, ensure adequate carbs pre-workout for energy and protein post-workout for repair.',
    'calorie.tip5Title': 'Fiber Benefits',
    'calorie.tip5Text': 'Adequate fiber intake supports digestion, keeps you full longer, and helps maintain steady energy levels throughout the day.',
    'calorie.tip6Title': 'Meal Timing',
    'calorie.tip6Text': 'Space your protein intake evenly throughout the day (every 3-4 hours) to maximize muscle protein synthesis.',

    // Programs page (UI only – program content stays one language)
    'programs.heroTitle': 'Personalized Calisthenics Programs',
    'programs.heroSlogan': 'Structured, Coach-Designed Training for Every Level',
    'programs.heroDesc': 'Take the guesswork out of training. Provide your level, rep maxes, and main sport, and I\'ll design a program that progresses safely and effectively — whether you\'re testing a free week or committing to a full 6- or 12-week plan.',
    'programs.heroNutrition': 'Track your performance and nutrition with personalized calorie and protein targets to fuel your growth and recovery.',
    'programs.howItWorks': 'How It Works',
    'programs.step1': 'Choose Your Plan',
    'programs.step1Desc': 'Free 1-week, 6-week, 12-week, or custom.',
    'programs.step2': 'Provide Your Stats',
    'programs.step2Desc': 'Level, rep maxes, height, weight, main sport.',
    'programs.step3': 'Receive Your Program',
    'programs.step3Desc': 'Sessions, sets, reps, sport-specific focus, warm-ups, coach notes.',
    'programs.step4': 'Delivered to Your Inbox',
    'programs.step4Desc': 'PDF sent to your email—ready for training.',
    'programs.yourMaxReps': 'Your rep maxes',
    'programs.formTitle': 'Your Stats',
    'programs.sectionPersonalInfo': 'Personal info',
    'programs.sectionContact': 'Contact',
    'programs.name': 'Name',
    'programs.namePlaceholder': 'e.g. Ahmed',
    'programs.nameHint': '',
    'programs.age': 'Age',
    'programs.agePlaceholder': '25',
    'programs.ageHint': '',
    'programs.errorAgeRequired': 'Please enter your age (13–120).',
    'programs.email': 'Contact Email',
    'programs.emailPlaceholder': 'you@example.com',
    'programs.emailHint': 'Optional for 1-week program.',
    'programs.emailHintFree': 'Your 1-week program will be sent to this email.',
    'programs.emailHintPaid': 'Your 6-week program will be sent to this email.',
    'programs.errorEmail': 'Please enter a valid email to receive your 6-week program.',
    'programs.errorEmailRequired': 'Please enter a valid email to receive your program.',
    'programs.errorNameRequired': 'Please enter your name.',
    'programs.errorHeightRequired': 'Please enter your height (100–250 cm).',
    'programs.errorWeightRequired': 'Please enter your weight (30–300 kg).',
    'programs.thanksTitle': 'Thanks!',
    'programs.verifyEmailHint': 'Please verify your email to receive your program.',
    'programs.checkSpamHint': 'Check your inbox and spam folder.',
    'programs.ok': 'OK',
    'programs.proceedToPayment': 'Proceed to payment page',
    'programs.sentToEmailTitle': 'Program sent to your email!',
    'programs.sentToEmailHint': 'Check your inbox (and spam folder) for your 6-week program with PDF attachment.',
    'programs.calisthenicsMainSport': 'Is calisthenics your main sport?',
    'programs.calisthenicsMainSportYes': 'Yes',
    'programs.calisthenicsMainSportNo': 'No',
    'programs.whatIsMainSport': 'What is your main sport?',
    'programs.mainSportHint': 'Your program will be tailored to your lifestyle and main sport.',
    'programs.goal': 'Your goal(s)',
    'programs.goalHint': 'Select one or more. Program will adapt to your goals.',
    'programs.goal_lose_weight': 'Lose Weight',
    'programs.goal_improve_endurance': 'Improve Endurance',
    'programs.goal_build_muscle': 'Build Muscle',
    'programs.goal_learn_skills': 'Learn New Skills',
    'programs.experienceLevel': 'Experience Level',
    'programs.beginner': 'Beginner',
    'programs.intermediate': 'Intermediate',
    'programs.advanced': 'Advanced',
    'programs.muscleUps': 'Muscle Ups',
    'programs.pullUps': 'Pull Ups',
    'programs.dips': 'Dips',
    'programs.pushUps': 'Push Ups',
    'programs.squats': 'Squats',
    'programs.legRaises': 'Leg Raises',
    'programs.burpees': 'Burpees',
    'programs.muscleUpHint': "Enter 0 if you can't do muscle-ups yet",
    'programs.generate': 'Generate Program',
    'programs.generating': 'Generating Program...',
    'programs.waitForProgram': 'Wait for your program',
    'programs.progressReady': 'Your program is ready!',
    'programs.statusAnalyzing': 'Analyzing your level...',
    'programs.statusBuilding': 'Building workout structure...',
    'programs.statusOptimizing': 'Optimizing reps & rest...',
    'programs.statusProgression': 'Applying progression logic...',
    'programs.statusIntensity': 'Calculating intensity...',
    'programs.statusFinalizing': 'Finalizing your program...',
    'programs.statusCrafting': 'Crafting your personalized program',
    'programs.statusSendingEmail': 'Sending your program to your email',
    'programs.statusSendingHint': 'Preparing your PDF and delivery…',
    'programs.statusHangTight': 'Hang tight — this may take 1–2 minutes. Almost there!',
    'programs.paymentSuccess': 'Payment successful!',
    'programs.paymentSending': 'Sending your 6-week program to your email…',
    'programs.paymentCompleteTitle': 'Your program has been sent!',
    'programs.paymentCompleteHint': 'Check your inbox (and spam folder) for the PDF attachment.',
    'programs.paymentErrorTitle': 'Could not send program',
    'programs.paymentErrorHint': 'Your payment was successful. Please contact us if you don\'t receive the email.',
    'programs.downloadPdf': 'Download PDF',
    'programs.downloading': 'Downloading…',
    'programs.downloaded': 'Downloaded!',
    'programs.downloadHint': 'Save it to your phone or print it out',
    'programs.readyHint': 'Grab your PDF and get after it.',
    'programs.pdf': 'PDF',
    'programs.week': 'Week',
    'programs.weekVolume': '60% of max',
    'programs.restLabel': 'Rest between sets:',
    'programs.errorReps': 'Please enter at least one exercise with reps > 0',
    'programs.errorGeneric': 'Failed to generate program. Please try again.',
    'programs.paymentCancelled': 'Payment was cancelled.',
    'programs.freeLimitReached': 'Free plan: 3 free generations limit reached. Try the 6-week plan for unlimited access.',
    'programs.freeAttemptsRemaining': 'Free generations this month: {{used}}/{{max}}',
    'programs.freeGenerationsLabel': 'Free generations',
    'programs.freeGenerationsHint': '3 free generations.',
    'programs.freeGenerationsLeft': 'left',
    'programs.plan': 'Plan',
    'programs.choosePlan': 'Choose the plan that fits your goals',
    'programs.plansIntro': 'Free week uses AI. Paid plans use coach-built progression.',
    'programs.planFree': 'Free — 1 week',
    'programs.planFreeName': 'Free Week',
    'programs.planFreePrice': '100% Free',
    'programs.planFreeDesc': '4 training sessions. Nutrition targets if you add stats. Delivered to your inbox.',
    'programs.planPaid': 'Paid — 6 weeks',
    'programs.planPaidName': '6 Weeks',
    'programs.planPaidPrice': '$39.99',
    'programs.planPaidDesc': '6 weeks, 5 training days. Nutrition, warm-ups, progressive overload.',
    'programs.planPaid12Desc': '12 weeks, 5 training days. Same structure, more volume.',
    'programs.planPaidBullet1': '5 sessions/week',
    'programs.planPaidBulletAutoLevel': 'Auto level detection from your rep maxes',
    'programs.planPaidBullet2': 'Nutrition targets + sample meal plan',
    'programs.planPaidBullet3': 'Warm-ups, progression, and deload week',
    'programs.planPaidBullet4': 'Coach-designed methods',
    'programs.planPaidBullet5': 'Built-in deload week for recovery and growth',
    'programs.planPaidBullet6': 'Coach-designed methods',
    'programs.planPaid12Bullet1': 'Full structured program for long-term progression',
    'programs.planPaid12Bullet2': 'Auto level detection and sport-specific adaptations',
    'programs.planCustomBullet1': 'Fully personalized',
    'programs.planCustomBullet2': 'Detailed inputs from you',
    'programs.planCustomBullet3': 'Tailored for your sport, level, and goals',
    'programs.planPaidHint': '5 sessions/week, nutrition guide, structured progression.',
    'programs.heightCm': 'Height (cm)',
    'programs.weightKg': 'Weight (kg)',
    'programs.heightWeightHint': 'Used for calorie and protein targets in your program.',
    'programs.yourData': 'Your data',
    'programs.nutritionTitle': 'Nutrition & calories',
    'programs.sampleMealsTitle': 'Sample daily meals',
    'programs.sampleMealsHint': 'Example meals with times and quantities (adjust to your preferences):',
    'programs.week1Intro': 'Intro – light intensity',
    'programs.week6Test': 'Peak & recovery',
    'programs.closingNote': 'Professional Coaching, Delivered Digitally. Every program follows real coaching rules, ensures safe progression, and adapts to your sport-specific needs. No guesswork, no generic workouts — just a program built for you.',

    // Privacy Policy
    'privacy.title': 'Privacy Policy',
    'privacy.lastUpdated': 'Last updated',
    'privacy.whoWeAre': 'Who we are',
    'privacy.dataWeCollect': 'Information we collect',
    'privacy.howWeUse': 'How we use your information',
    'privacy.cookies': 'Cookies and similar technologies',
    'privacy.advertising': 'Advertising and Google AdSense',
    'privacy.dataRetention': 'Data retention and security',
    'privacy.yourRights': 'Your rights',
    'privacy.changes': 'Changes to this policy',
    'privacy.contact': 'Contact us',
    'privacy.backToHome': 'Back to Home',

    'about.title': 'About Us',
    'about.subtitle': 'Premium calisthenics equipment for Algeria. Built for athletes, delivered with care.',
    'about.metaDescription': 'REPS-DZ offers premium calisthenics equipment in Algeria. Learn about our mission, quality standards, and local support.',
    'about.whoWeAre': 'Who we are',
    'about.whoWeAreText': 'REPS-DZ is an Algerian brand focused on bringing premium calisthenics and fitness equipment to athletes and home trainers. We stock pull-up bars, parallettes, resistance bands, and accessories designed for real training—no flimsy hardware, just gear that holds up to daily use.',
    'about.mission': 'Our mission',
    'about.missionText': 'We believe everyone deserves access to quality equipment. Our mission is to help you train safely at home with durable, well-designed products and clear advice. We offer guides, a free workout program generator, and a calorie calculator so you can focus on training—not guessing.',
    'about.builtForAthletes': 'Built for Athletes',
    'about.builtDesc': 'Professional-grade equipment designed by calisthenics experts.',
    'about.fastDelivery': 'Fast Delivery',
    'about.fastDesc': 'Quick shipping across Algeria—get your gear in 24–48 hours.',
    'about.quality': 'Premium Quality',
    'about.qualityDesc': 'Durable, battle-tested materials that last for years.',
    'about.localSupport': 'Local Support',
    'about.supportDesc': 'Expert customer service in Algeria—we speak your language.',
    'about.contact': 'Get in touch',
    'about.contactText': "Have a question or need help choosing equipment? We're here to help. Reach out via our About Me page or by phone. We ship across Algeria and stand behind our products.",
    'about.contactUs': 'About Me',
    'about.shop': 'Shop',
    'guides.relatedGuides': 'Related guides',
    'guides.shopCta': 'Need equipment?',
    'guides.shopLink': 'Shop pull-up bars and more',
  },
  ar: {
    // Header
    'header.home': 'الرئيسية',
    'header.shop': 'المتجر',
    'header.programs': 'البرامج',
    'header.calculator': 'حاسبة السعرات',
    'header.calorieCalculator': 'حاسبة السعرات',
    'header.contact': 'عني',
    'header.feedback': 'تعليقات',
    'header.guides': 'أدلة ونصائح',
    'header.cart': 'السلة',
    'header.admin': 'الإدارة',
    'header.logout': 'تسجيل الخروج',
    
    // Cart
    'cart.title': 'سلة التسوق',
    'cart.empty': 'سلة التسوق فارغة',
    'cart.emptyDesc': 'يبدو أنك لم تضيف أي منتجات إلى سلة التسوق بعد.',
    'cart.continueShopping': 'متابعة التسوق',
    'cart.items': 'منتج',
    'cart.itemsPlural': 'منتجات',
    'cart.inCart': 'في سلة التسوق',
    'cart.subtotal': 'المجموع الفرعي',
    'cart.shipping': 'الشحن',
    'cart.tax': 'الضريبة',
    'cart.total': 'الإجمالي',
    'cart.freeShipping': 'مجاني',
    'cart.freeShippingProgress': 'تقدم الشحن المجاني',
    'cart.addMore': 'أضف {amount} دج إضافي للحصول على شحن مجاني!',
    'cart.freeShippingQualified': 'أنت مؤهل للحصول على شحن مجاني!',
    'cart.proceedToCheckout': 'الانتقال إلى الدفع',
    'cart.features.freeShipping': 'شحن مجاني',
    'cart.features.securePayment': 'دفع آمن',
    'cart.features.support': 'دعم 24/7',
    
    // Product Detail
    'product.addToCart': 'أضف إلى السلة',
    'product.buyNow': 'اشتري الآن',
    'product.outOfStock': 'نفدت الكمية',
    'product.inStock': 'متوفر',
    'product.lowStock': 'كمية قليلة',
    'product.lowStockWarning': 'كمية قليلة. اطلب قريباً.',
    'product.quantity': 'الكمية',
    'product.size': 'الحجم',
    'product.color': 'اللون',
    'product.description': 'الوصف',
    'product.specifications': 'المواصفات',
    'product.usage': 'الاستخدام',
    'product.noSpecs': 'لا توجد مواصفات متاحة.',
    'product.reviews': 'تقييمات',
    'product.category': 'الفئة',
    'product.status': 'الحالة',
    'product.youMayAlsoLike': 'قد يعجبك أيضاً',
    
    // Order
    'order.title': 'إتمام الطلب',
    'order.subtitle': 'راجع تفاصيل المنتج واملأ معلوماتك',
    'order.productDetails': 'تفاصيل المنتج',
    'order.clientInfo': 'معلومات العميل',
    'order.fullName': 'الاسم الكامل',
    'order.phone': 'رقم الهاتف',
    'order.deliveryType': 'نوع التوصيل',
    'order.deliveryHome': 'المنزل',
    'order.deliveryHomeDesc': 'التوصيل إلى عنوانك',
    'order.deliveryStopDesk': 'نقطة الاستلام',
    'order.deliveryStopDeskDesc': 'الاستلام من نقطة التوصيل (خصم 30%)',
    'order.wilaya': 'الولاية',
    'order.selectWilaya': 'اختر الولاية',
    'order.selectCommune': 'اختر البلدية',
    'order.commune': 'البلدية',
    'order.exactAddress': 'العنوان الدقيق',
    'order.exactAddressOptional': '(اختياري)',
    'order.exactAddressPlaceholder': 'عنوان الشارع، رقم المبنى، الشقة، إلخ.',
    'order.orderSummary': 'ملخص الطلب',
    'order.delivery': 'التوصيل',
    'order.placeOrder': 'تأكيد الطلب',
    'order.processing': 'جاري المعالجة...',
    'order.confirmed': 'تم تأكيد الطلب!',
    'order.successSingle': 'تم تقديم طلبك لـ',
    'order.successMultiple': 'تم تقديم طلبك لـ',
    'order.successEnd': 'بنجاح.',
    'order.successItems': 'منتج',
    'order.successItemsPlural': 'منتجات',
    'order.redirecting': 'جاري إعادة التوجيه إلى الصفحة الرئيسية...',
    'order.note': 'ملاحظة:',
    'order.noteText': 'ستتلقى مكالمة تأكيد بعد تقديم طلبك.',
    'order.required': '*',
    
    // Shop
    'shop.title': 'المتجر',
    'shop.filter': 'تصفية',
    'shop.sort': 'ترتيب',
    'shop.allCategories': 'جميع الفئات',
    'shop.priceRange': 'نطاق السعر',
    'shop.search': 'ابحث عن المنتجات...',
    'shop.noProducts': 'لم يتم العثور على منتجات',
    'shop.loading': 'جاري التحميل...',
    'shop.sortName': 'الاسم (أ-ي)',
    'shop.sortPriceLow': 'السعر (من الأقل للأعلى)',
    'shop.sortPriceHigh': 'السعر (من الأعلى للأقل)',
    'shop.sortRating': 'الأعلى تقييماً',
    'shop.noProductsDesc': 'لم نتمكن من العثور على أي منتجات تطابق عوامل التصفية الخاصة بك.',
    
    // Home
    'home.shopByCategory': 'تسوق حسب الفئة',
    'home.shopByCategoryDesc': 'ابحث عن المعدات المثالية المصممة لاحتياجاتك التدريبية.',
    'home.bestseller': 'الأكثر مبيعاً',
    'home.toprated': 'الأعلى تقييماً',
    'home.essential': 'أساسي',
    'home.builtforathletes': 'مصمم للرياضيين',
    'home.builtforathletesDesc': 'معدات احترافية مصممة من قبل خبراء الكاليسثينكس',
    'home.fastdelivery': 'توصيل سريع',
    'home.fastdeliveryDesc': 'شحن سريع عبر الجزائر - احصل على معداتك في 24-48 ساعة',
    'home.premiumquality': 'جودة عالية',
    'home.premiumqualityDesc': 'مواد متينة ومختبرة تدوم لسنوات',
    'home.localsupport': 'دعم محلي',
    'home.localsupportDesc': 'خدمة عملاء متخصصة في الجزائر - نتحدث لغتك',
    'home.bestSellers': 'الأكثر مبيعاً',
    'home.topRated': 'أفضل المعدات المختارة من قبل الأبطال.',
    'home.viewAll': 'عرض الكل',
    'home.startJourney': 'ابدأ',
    'home.journey': 'رحلتك',
    'home.journeyDesc': 'جهز نفسك بأفضل الأدوات في اللعبة. انضم إلى الحركة اليوم.',
    'home.guidesTitle': 'أدلة ونصائح',
    'home.guidesDesc': 'نصائح الخبراء حول المعدات والكاليستينكس والتدريب في المنزل.',
    'home.readGuides': 'اقرأ الأدلة',
    'home.programGeneratorTitle': 'مولّد برنامج تدريبي مجاني',
    'home.programGeneratorDesc': 'احصل على برنامج كاليستينكس أسبوعي شخصي حسب مستواك وأعلى عدد تكرارات. أدخل أرقامك، انشئ برنامجك، وحمّل PDF للمتابعة.',
    'home.generateProgram': 'إنشاء البرنامج',
    'home.calorieCalculatorTitle': 'حاسبة السعرات',
    'home.calorieCalculatorDesc': 'احسب سعراتك الحرارية اليومية وأهداف الماكرو (بروتين، كربوهيدرات، دهون) حسب عمرك ووزنك وطولك ومستوى نشاطك.',
    'home.calculateCalories': 'حساب السعرات',
    'guides.title': 'أدلة ونصائح',
    'guides.subtitle': 'نصائح الخبراء حول اختيار المعدات والبدء في الكاليستينكس والتدريب بأمان في المنزل.',
    'guides.readMore': 'اقرأ الدليل الكامل',
    'guides.backToGuides': 'العودة إلى جميع الأدلة',
    'home.shopNow': 'تسوق الآن',
    'home.fastShipping': 'شحن سريع',
    'home.securePayment': 'دفع آمن',
    'home.support24': 'دعم 24/7',
    'home.premiumQuality': 'جودة عالية',
    
    // About Me (formerly Contact)
    'aboutMe.title': 'عني',
    'aboutMe.subtitle': 'رياضي كاليستينكس محترف ومؤسس Toufik Calisthenics',
    'aboutMe.metaDesc': 'توفيق رحماني – رياضي كاليستينكس تنافسي جزائري محترف. بطل وطني مرتين، المركز الثالث في بطولة العالم WSWCF صوفيا.',
    'aboutMe.whoAmI': 'من أنا',
    'aboutMe.intro': 'توفيق رحماني — رياضي كاليستينكس تنافسي جزائري محترف بأكثر من خمس سنوات من الخبرة وعناوين وطنية ودولية.',
    'aboutMe.experience': 'الخبرة والخلفية',
    'aboutMe.experienceDesc': 'أكثر من خمس سنوات من التدريب والمنافسة في الكاليستينكس. رياضي محترف يمثل الجزائر على المستوى الوطني والعالمي.',
    'aboutMe.achievements': 'الإنجازات',
    'aboutMe.nationalChampion': 'بطل وطني',
    'aboutMe.nationalChampionDesc': 'المركز الأول مرتين — بطل وطني في التحمل.',
    'aboutMe.wswcf': 'بطولة العالم WSWCF',
    'aboutMe.wswcfDesc': 'المركز الثالث — بطولة العالم WSWCF، صوفيا (القوة).',
    'aboutMe.fiboArabia': 'كأس Fibo Arabia',
    'aboutMe.fiboArabiaDesc': 'المركز الرابع — كأس Fibo Arabia للتحمل في الكاليستينكس.',
    'aboutMe.getInTouch': 'تواصل معي',
    'aboutMe.chatWhatsApp': 'محادثة واتساب',
    'aboutMe.whatsappMessage': 'مرحباً توفيق! أود معرفة المزيد.',
    'contact.title': 'اتصل بنا',
    'contact.subtitle': 'هل لديك سؤال أو تحتاج إلى مساعدة؟ نحن هنا للمساعدة!',
    'contact.sendMessage': 'أرسل لنا رسالة',
    'contact.name': 'الاسم الكامل',
    'contact.email': 'عنوان البريد الإلكتروني',
    'contact.subject': 'الموضوع',
    'contact.message': 'الرسالة',
    'contact.send': 'إرسال الرسالة',
    'contact.sending': 'جاري الإرسال...',
    'contact.phone': 'الهاتف',
    'contact.location': 'الموقع',
    'contact.followUs': 'تابعنا',
    'contact.formDesc': 'سنرد عليك في غضون 24 ساعة.',
    'contact.whatsappMessage': 'مرحباً REPS-DZ! أود معرفة المزيد عن منتجاتكم.',
    'contact.subjectPlaceholder': 'كيف يمكننا مساعدتك؟',
    'contact.messagePlaceholder': 'رسالتك هنا...',
    
    // Footer
    'footer.about': 'حول',
    'footer.quickLinks': 'روابط سريعة',
    'footer.contact': 'اتصل',
    'footer.followUs': 'تابعنا',
    'footer.rights': 'جميع الحقوق محفوظة.',
    
    // Common
    'common.back': 'رجوع',
    'common.loading': 'جاري التحميل...',
    'common.error': 'خطأ',
    'common.success': 'نجح',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.view': 'عرض',
    'common.close': 'إغلاق',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.clear': 'مسح',
    'common.result': 'النتيجة',
    'common.results': 'نتائج',
    'common.show': 'عرض',

    // Calorie Calculator page
    'calorie.title': 'السعرات والماكرو',
    'calorie.calculator': 'الحاسبة',
    'calorie.subtitle': 'احسب احتياجك اليومي من السعرات والماكرو حسب مقاييس جسمك ومستوى نشاطك',
    'calorie.wantFullGuide': 'تريد فهم السعرات لخسارة الدهون؟',
    'calorie.readCaloriesGuide': 'اقرأ دليل السعرات الكامل',
    'calorie.yourInfo': 'معلوماتك',
    'calorie.yourName': 'اسمك',
    'calorie.yourNamePlaceholder': 'مثال: أحمد',
    'calorie.gender': 'الجنس',
    'calorie.male': 'ذكر',
    'calorie.female': 'أنثى',
    'calorie.height': 'الطول (سم)',
    'calorie.weight': 'الوزن (كغ)',
    'calorie.age': 'العمر (بالسنوات)',
    'calorie.activityLevel': 'مستوى النشاط',
    'calorie.selectActivity': 'اختر مستوى النشاط',
    'calorie.activityLow': 'منخفض (قليل الحركة)',
    'calorie.activityModerate': 'متوسط (تمارين 3-5 أيام/أسبوع)',
    'calorie.activityHigh': 'عالي (تمارين 6-7 أيام/أسبوع)',
    'calorie.calculate': 'احسب',
    'calorie.calculating': 'جاري الحساب...',
    'calorie.errorSelectGender': 'يرجى اختيار الجنس',
    'calorie.errorHeight': 'يرجى إدخال طول صحيح (1-250 سم)',
    'calorie.errorWeight': 'يرجى إدخال وزن صحيح (1-300 كغ)',
    'calorie.errorAge': 'يرجى إدخال عمر صحيح (1-120 سنة)',
    'calorie.errorGeneric': 'خطأ في الحساب. تحقق من المدخلات وحاول مرة أخرى.',
    'calorie.dailyTarget': 'الهدف اليومي من السعرات',
    'calorie.basedOnProfile': 'حسب بياناتك ومستوى النشاط',
    'calorie.bmrAtRest': 'معدل الأيض الأساسي (في الراحة)',
    'calorie.bmrDesc': 'السعرات التي يحرقها جسمك في الراحة التامة (Mifflin-St Jeor)',
    'calorie.macroTargets': 'أهداف الماكرو',
    'calorie.perDay': '/يوم',
    'calorie.fiberNote': 'الألياف:',
    'calorie.fiberRecommended': 'غ/يوم موصى به (14غ لكل 1000 سعرة)',
    'calorie.fitnessTips': 'نصائح لياقة',
    'calorie.macroCalories': 'السعرات',
    'calorie.macroProtein': 'البروتين',
    'calorie.macroCarbs': 'الكربوهيدرات',
    'calorie.macroFat': 'الدهون',
    'calorie.macroFiber': 'الألياف',
    'calorie.tip1Title': 'توقيت البروتين',
    'calorie.tip1Text': 'تناول 20-30 غ من البروتين خلال 30 دقيقة بعد التمرين لتعافي ونمو العضلات.',
    'calorie.tip2Title': 'ترطيب الجسم',
    'calorie.tip2Text': 'اشرب 2-3 لترات من الماء يومياً. العضلات تحتاج ترطيباً جيداً لأداء أفضل وتعافي.',
    'calorie.tip3Title': 'الراحة والنوم',
    'calorie.tip3Text': 'نم 7-9 ساعات. هرمون النمو يبلغ ذروته في النوم العميق الضروري لتعافي العضلات.',
    'calorie.tip4Title': 'التغذية والقوة',
    'calorie.tip4Text': 'لتدريب القوة: كربوهيدرات قبل التمرين للطاقة وبروتين بعده للإصلاح.',
    'calorie.tip5Title': 'فوائد الألياف',
    'calorie.tip5Text': 'الألياف تدعم الهضم وتشبعك وتساعد في استقرار الطاقة خلال اليوم.',
    'calorie.tip6Title': 'توقيت الوجبات',
    'calorie.tip6Text': 'وزّع البروتين على اليوم (كل 3-4 ساعات) لتعظيم تخليق بروتين العضلات.',

    // Programs page (UI only)
    'programs.heroTitle': 'برامج كاليسثينكس شخصية',
    'programs.heroSlogan': 'تدريب منظم مصمم من مدرب لكل المستويات',
    'programs.heroDesc': 'أزل التخمين من التدريب. أعطني مستواك وأقصى تكراراتك ورياضتك الأساسية، وأصمم لك برنامجاً يتقدم بأمان وفعالية — سواءً تجرّب أسبوعاً مجانياً أو تلتزم بخطة 6 أو 12 أسبوعاً.',
    'programs.heroNutrition': 'تتبع أداءك وتغذيتك بأهداف سعرات وبروتين شخصية لتغذية نموك وتعافيك.',
    'programs.howItWorks': 'كيف يعمل',
    'programs.step1': 'اختر خطتك',
    'programs.step1Desc': 'أسبوع مجاني، 6 أسابيع، 12 أسبوع، أو مخصص.',
    'programs.step2': 'أعطني بياناتك',
    'programs.step2Desc': 'مستوى، أقصى تكرارات، طول، وزن، الرياضة الأساسية.',
    'programs.step3': 'استلم برنامجك',
    'programs.step3Desc': 'جلسات، مجموعات، تكرارات، تركيز رياضي، إحماء، ملاحظات المدرب.',
    'programs.step4': 'يُرسل إلى بريدك',
    'programs.step4Desc': 'PDF يُرسل إلى بريدك—جاهز للتدريب.',
    'programs.yourMaxReps': 'أقصى تكراراتك',
    'programs.formTitle': 'بياناتك',
    'programs.sectionPersonalInfo': 'المعلومات الشخصية',
    'programs.sectionContact': 'التواصل',
    'programs.name': 'الاسم',
    'programs.namePlaceholder': 'مثال: أحمد',
    'programs.nameHint': '',
    'programs.age': 'العمر',
    'programs.agePlaceholder': '25',
    'programs.ageHint': '',
    'programs.errorAgeRequired': 'يرجى إدخال عمرك (13–120).',
    'programs.email': 'البريد الإلكتروني للتواصل',
    'programs.emailPlaceholder': 'you@example.com',
    'programs.emailHint': 'اختياري للبرنامج الأسبوعي.',
    'programs.emailHintFree': 'سيُرسل برنامج الأسبوع الواحد إلى هذا البريد.',
    'programs.emailHintPaid': 'سيُرسل برنامج الـ 6 أسابيع إلى هذا البريد.',
    'programs.errorEmail': 'يرجى إدخال بريد إلكتروني صحيح لاستلام برنامج الـ 6 أسابيع.',
    'programs.errorEmailRequired': 'يرجى إدخال بريد إلكتروني صحيح لاستلام برنامجك.',
    'programs.errorNameRequired': 'يرجى إدخال اسمك.',
    'programs.errorHeightRequired': 'يرجى إدخال طولك (100–250 سم).',
    'programs.errorWeightRequired': 'يرجى إدخال وزنك (30–300 كغ).',
    'programs.thanksTitle': 'شكراً!',
    'programs.verifyEmailHint': 'يرجى التحقق من بريدك لاستلام برنامجك.',
    'programs.checkSpamHint': 'تحقق من صندوق الوارد ومجلد السبام.',
    'programs.ok': 'موافق',
    'programs.proceedToPayment': 'متابعة إلى صفحة الدفع',
    'programs.sentToEmailTitle': 'تم إرسال البرنامج إلى بريدك!',
    'programs.sentToEmailHint': 'تحقق من صندوق الوارد (ومجلد السبام) لبرنامج الـ 6 أسابيع.',
    'programs.calisthenicsMainSport': 'هل الكاليسثينكس رياضتك الأساسية؟',
    'programs.calisthenicsMainSportYes': 'نعم',
    'programs.calisthenicsMainSportNo': 'لا',
    'programs.whatIsMainSport': 'ما هي رياضتك الأساسية؟',
    'programs.mainSportHint': 'سيُعدّ برنامجك حسب أسلوب حياتك ورياضتك الأساسية.',
    'programs.goal': 'هدفك',
    'programs.goalHint': 'اختر واحداً أو أكثر. سيتكيّف البرنامج مع أهدافك.',
    'programs.goal_lose_weight': 'خسارة الوزن',
    'programs.goal_improve_endurance': 'تحسين التحمل',
    'programs.goal_build_muscle': 'بناء العضلات',
    'programs.goal_learn_skills': 'تعلم مهارات جديدة',
    'programs.experienceLevel': 'مستوى الخبرة',
    'programs.beginner': 'مبتدئ',
    'programs.intermediate': 'متوسط',
    'programs.advanced': 'متقدم',
    'programs.muscleUps': 'مسك أب',
    'programs.pullUps': 'سحب',
    'programs.dips': 'غطس',
    'programs.pushUps': 'ضغط',
    'programs.squats': 'قرفصاء',
    'programs.legRaises': 'رفع رجل',
    'programs.burpees': 'بربيس',
    'programs.muscleUpHint': 'أدخل 0 إن لم تتمكن من المسك أب بعد',
    'programs.generate': 'ولّد البرنامج',
    'programs.generating': 'جاري التوليد...',
    'programs.waitForProgram': 'انتظر برنامجك',
    'programs.progressReady': 'برنامجك جاهز!',
    'programs.statusAnalyzing': 'جاري تحليل مستواك...',
    'programs.statusBuilding': 'جاري بناء هيكل التمارين...',
    'programs.statusOptimizing': 'جاري تحسين التكرارات والراحة...',
    'programs.statusProgression': 'تطبيق منطق التدرج...',
    'programs.statusIntensity': 'حساب الشدة...',
    'programs.statusFinalizing': 'جاري إنهاء برنامجك...',
    'programs.statusCrafting': 'إنشاء برنامجك الشخصي',
    'programs.statusSendingEmail': 'جاري إرسال برنامجك إلى بريدك',
    'programs.statusSendingHint': 'جاري تحضير PDF والإرسال…',
    'programs.paymentSuccess': 'تم الدفع بنجاح!',
    'programs.paymentSending': 'جاري إرسال برنامج الـ 6 أسابيع إلى بريدك…',
    'programs.paymentCompleteTitle': 'تم إرسال برنامجك!',
    'programs.paymentCompleteHint': 'تحقق من صندوق الوارد (ومجلد السبام) للحصول على ملف PDF.',
    'programs.paymentErrorTitle': 'تعذر إرسال البرنامج',
    'programs.paymentErrorHint': 'تم الدفع بنجاح. يرجى التواصل معنا إن لم يصلك البريد.',
    'programs.downloadPdf': 'تحميل PDF',
    'programs.downloading': 'جاري التحميل…',
    'programs.downloaded': 'تم التحميل!',
    'programs.downloadHint': 'احفظه على هاتفك أو اطبع النسخة',
    'programs.readyHint': 'احصل على PDF وابدأ التدريب.',
    'programs.pdf': 'PDF',
    'programs.week': 'الأسبوع',
    'programs.weekVolume': '60% من الأقصى',
    'programs.restLabel': 'الراحة بين المجموعات:',
    'programs.errorReps': 'يرجى إدخال تمرين واحد على الأقل بعدد تكرارات > 0',
    'programs.errorGeneric': 'فشل توليد البرنامج. حاول مرة أخرى.',
    'programs.paymentCancelled': 'تم إلغاء الدفع.',
    'programs.freeLimitReached': 'الخطة المجانية: تم استنفاد 3 توليدات مجانية. جرّب خطة الـ 6 أسابيع.',
    'programs.freeAttemptsRemaining': 'البرامج المجانية هذا الشهر: {{used}}/{{max}}',
    'programs.freeGenerationsLabel': 'التوليدات المجانية',
    'programs.freeGenerationsHint': '3 توليدات مجانية.',
    'programs.freeGenerationsLeft': 'متبقية',
    'programs.plan': 'الخطة',
    'programs.choosePlan': 'اختر الخطة التي تناسب أهدافك',
    'programs.plansIntro': 'الأسبوع المجاني بالذكاء الاصطناعي. الخطط المدفوعة بتدرج مصمم من مدرب.',
    'programs.planFree': 'مجاني — أسبوع واحد',
    'programs.planFreeName': 'أسبوع مجاني',
    'programs.planFreePrice': 'مجاني 100%',
    'programs.planFreeDesc': '4 جلسات تدريب. أهداف تغذية إن أضفت بياناتك. يُرسل إلى بريدك.',
    'programs.planPaid': 'مدفوع — 6 أسابيع',
    'programs.planPaidName': '6 أسابيع',
    'programs.planPaidPrice': '$39.99 USD',
    'programs.planPaidDesc': '6 أسابيع، 5 أيام تدريب. تغذية، إحماء، حمل تقدمي.',
    'programs.planPaid12Desc': '12 أسبوعاً، 5 أيام تدريب. نفس الهيكل، حجم أكثر.',
    'programs.planPaidBullet1': '5 جلسات أسبوعياً',
    'programs.planPaidBulletAutoLevel': 'كشف تلقائي للمستوى من أقصى تكراراتك',
    'programs.planPaidBullet2': 'أهداف تغذية + خطة وجبات نموذجية',
    'programs.planPaidBullet3': 'إحماء وتدرج وأسبوع راحة',
    'programs.planPaidBullet4': 'أساليب مصممة من مدرب',
    'programs.planPaidBullet5': 'أسبوع راحة مدمج للتعافي والنمو',
    'programs.planPaidBullet6': 'أساليب مصممة من مدرب',
    'programs.planPaid12Bullet1': 'برنامج منسق كامل للتقدم طويل المدى',
    'programs.planPaid12Bullet2': 'كشف تلقائي للمستوى وتكييفات رياضية',
    'programs.planCustomBullet1': 'شخصي بالكامل',
    'programs.planCustomBullet2': 'مدخلات مفصّلة منك',
    'programs.planCustomBullet3': 'مصمم لرياضتك ومستواك وأهدافك',
    'programs.planPaidHint': '5 جلسات أسبوعياً، دليل تغذية، تدرج منظم.',
    'programs.heightCm': 'الطول (سم)',
    'programs.weightKg': 'الوزن (كغ)',
    'programs.heightWeightHint': 'يُستخدم لأهداف السعرات والبروتين في برنامجك.',
    'programs.yourData': 'بياناتك',
    'programs.nutritionTitle': 'التغذية والسعرات',
    'programs.sampleMealsTitle': 'وجبات يومية نموذجية',
    'programs.sampleMealsHint': 'أمثلة وجبات مع الأوقات والكميات (عدّل حسب تفضيلاتك):',
    'programs.week1Intro': 'تمهيد – شدة خفيفة',
    'programs.week6Test': 'الذروة والتعافي',
    'programs.closingNote': 'تدريب احترافي يُقدّم رقمياً. كل برنامج يتبع قواعد التدريب الحقيقية، يضمن تقدماً آمناً، ويتكيّف مع احتياجات رياضتك. بدون تخمين، بدون تمارين عامة — فقط برنامج مبني من أجلك.',

    'privacy.title': 'سياسة الخصوصية',
    'privacy.lastUpdated': 'آخر تحديث',
    'privacy.whoWeAre': 'من نحن',
    'privacy.dataWeCollect': 'المعلومات التي نجمعها',
    'privacy.howWeUse': 'كيف نستخدم معلوماتك',
    'privacy.cookies': 'ملفات تعريف الارتباط والتقنيات المماثلة',
    'privacy.advertising': 'الإعلانات و Google AdSense',
    'privacy.dataRetention': 'الاحتفاظ بالبيانات والأمان',
    'privacy.yourRights': 'حقوقك',
    'privacy.changes': 'تغييرات على هذه السياسة',
    'privacy.contact': 'اتصل بنا',
    'privacy.backToHome': 'العودة إلى الرئيسية',

    'about.title': 'من نحن',
    'about.subtitle': 'معدات كاليستينكس متميزة للجزائر. مصممة للرياضيين، تُقدّم بعناية.',
    'about.metaDescription': 'REPS-DZ تقدم معدات كاليستينكس متميزة في الجزائر. تعرف على مهمتنا ومعايير الجودة والدعم المحلي.',
    'about.whoWeAre': 'من نحن',
    'about.whoWeAreText': 'REPS-DZ علامة جزائرية تركز على تقديم معدات كاليستينكس ولياقة عالية الجودة للرياضيين والمدربين في المنزل.',
    'about.mission': 'مهمتنا',
    'about.missionText': 'نؤمن بأن الجميع يستحق الوصول إلى معدات ذات جودة. مهمتنا مساعدتك على التدريب بأمان في المنزل.',
    'about.builtForAthletes': 'مصممة للرياضيين',
    'about.builtDesc': 'معدات احترافية مصممة من خبراء كاليستينكس.',
    'about.fastDelivery': 'توصيل سريع',
    'about.fastDesc': 'شحن سريع عبر الجزائر—استلم طلبك خلال 24–48 ساعة.',
    'about.quality': 'جودة متميزة',
    'about.qualityDesc': 'مواد متينة ومجرّبة تدوم لسنوات.',
    'about.localSupport': 'دعم محلي',
    'about.supportDesc': 'خدمة عملاء متخصصة في الجزائر—نتحدث لغتك.',
    'about.contact': 'تواصل معنا',
    'about.contactText': 'لديك سؤال أو تحتاج مساعدة في اختيار المعدات؟ تواصل معنا عبر صفحة عني أو بالهاتف.',
    'about.contactUs': 'عني',
    'about.shop': 'المتجر',
    'guides.relatedGuides': 'أدلة ذات صلة',
    'guides.shopCta': 'تحتاج معدات؟',
    'guides.shopLink': 'تسوق قضبان السحب والمزيد',
  }
};

const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  const switchLanguage = (lang) => {
    setLanguage(lang);
  };

  return (
    <LanguageContext.Provider value={{ language, switchLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export { LanguageContext, LanguageProvider };
